### PR TITLE
Allow for custom api host url

### LINKED ISSUE #71: [REQUEST] Allow for different API URL/endpoint
I don't want to have my API running at `/api` and would rather have it on another (sub-)domain.
I would propose using ENVs (preferably) to read where the API is running at and default to `/api` so when running Docker you could just pass an ENV and read it using `process.env.<key>`

### PR DESCRIPTION
**Pull request by kdev**
closes #71 

IMPORTANT: The URL should include `http(s)://`

### CODE REVIEW

**Comment by PhlexPlexico** [comment]
I do like the idea of this as it does give some more refinement for users to choose the endpoint they wish to have. Has this been tested, though? I'd be wary to change all these endpoint calls and not have them work 😅 so long as it's tested I'll merge it in!

**Comment by kdev** [comment]
there is no reason it shouldn't tbh, because I am not changing anything critical but will test it anyways

**Comment by kdev** [comment]
Using ENVs seems to be quite complicated as described [here](https://cli.vuejs.org/guide/mode-and-env.html)

**Comment by kdev** [comment]
Should I do some documentation work on this? Or would you like to do it?

**Comment by PhlexPlexico** [comment]
If you could do the documentation that would be wonderful :) it seems fairly straightforward, but would be nice to append to the README, especially for the Dockerfile as well.

**Comment by kdev** [comment]
Will do ^^

**Comment by kdev** [comment]
This is ready to be merged!

**Review by PhlexPlexico — APPROVED** [review]

**Pull request merged**
