### PR TITLE
Pass env vars into the container

### LINKED ISSUE #155: [Request] Pass "process.env?.VUE_APP_G5V_API_URL" into the docker container

### PR DESCRIPTION
**Pull request by kubo6472**
Fixes #155

### CODE REVIEW

**Review by PhlexPlexico — CHANGES_REQUESTED** [review]
Thanks for the contribution! However, just to keep in line with what the API does, I would like to request four things:
- Update the README to reflect these changes for the DockerfileLight section and what is needed to build/change the API location.
- Include `.env` in the `.gitignore`
- Adjust the process in the DockerfileFull to use the .env instead of build args/update documentation as necessary.
- Use `.env.template` and call a `COPY` command to make it `.env`. Just to keep inline with other projects, even if there are no secrets I wouldn't want someone hardcoding that value and making a PR.

Thanks!

**Comment by kubo6472** [comment]
Actually, none of these fixes help my very obscure issue, would you mind checking that this: https://g5api.tjm.sk/api responds "not found" and it is in fact coming from g5api? on the subdomain it works, but the moment I add any path, it refuses to work and I can't get G5V to edit its API URL variable.

I will need to do some local testing with G5V to truly find how to do envvars, then how to make them docker friendly. But the first main issue is what does G5API want to see as a path, and why does it not cooperate. P.S. this is my second dig at using Traefik instead of Nginx or Caddy for this. Works for frontend, but for the love of god I can't get the API to function on a path.

**Comment by PhlexPlexico** [comment]
I'm not too sure then, that's a tech I haven't used. I would assume it's because the reverse proxy isn't working, just the base URL doesn't seem to work either. I'm assuming it's just a rewrite that's failing from `api` -> node server... Sorry I can't really help out much with it 😅

**Comment by kubo6472** [comment]
Thanks, will let you know if I come up with anything

**Comment by kubo6472** [comment]
It works. I have no idea how yet. No idea if this is still needed. I don't need this now, but I could attempt some breakthrough, if desired. I will close this, though, and do a small cleanup.

**Pull request closed without merging**
